name: Issue or feature request related to the GUI
description: Any report, issue or feature request related to the GUI
labels: [GUI]
body:
- type: checkboxes
  id: acknowledgement
  attributes:
    label: Issues, reports or feature requests related to the GUI
    description: https://github.com/Nintondo/bellscoinV3/issues
    options:
      - label: I think this issue should be opened here
        required: true
- type: textarea
  id: gui-request
  attributes:
    label: Report
  validations:
    required: true
