.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bellscoin_qt test_bellscoin_qt
clean: FORCE
	$(MAKE) -C .. bellscoin_qt_clean test_bellscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bellscoin_qt_check
bellscoin-qt bellscoin-qt.exe: FORCE
	 $(MAKE) -C .. bells_qt
apk: FORCE
	$(MAKE) -C .. bellscoin_qt_apk
